# Lista oficial de 38 animales para la lotería
ANIMALES = [
    {"id": "0",  "numero": "0",  "nombre": "DELFIN"},
    {"id": "00", "numero": "00", "nombre": "BALLENA"},
    {"id": 1,  "numero": "01", "nombre": "CARNERO"},
    {"id": 2,  "numero": "02", "nombre": "TORO"},
    {"id": 3,  "numero": "03", "nombre": "CIEMPIES"},
    {"id": 4,  "numero": "04", "nombre": "ALACRAN"},
    {"id": 5,  "numero": "05", "nombre": "LEON"},
    {"id": 6,  "numero": "06", "nombre": "RANA"},
    {"id": 7,  "numero": "07", "nombre": "PERICO"},
    {"id": 8,  "numero": "08", "nombre": "RATON"},
    {"id": 9,  "numero": "09", "nombre": "AGUILA"},
    {"id": 10, "numero": "10", "nombre": "TIGRE"},
    {"id": 11, "numero": "11", "nombre": "GATO"},
    {"id": 12, "numero": "12", "nombre": "CABALLO"},
    {"id": 13, "numero": "13", "nombre": "MONO"},
    {"id": 14, "numero": "14", "nombre": "PALOMA"},
    {"id": 15, "numero": "15", "nombre": "ZORRO"},
    {"id": 16, "numero": "16", "nombre": "OSO"},
    {"id": 17, "numero": "17", "nombre": "PAVO"},
    {"id": 18, "numero": "18", "nombre": "BURRO"},
    {"id": 19, "numero": "19", "nombre": "CHIVO"},
    {"id": 20, "numero": "20", "nombre": "COCHINO"},
    {"id": 21, "numero": "21", "nombre": "GALLO"},
    {"id": 22, "numero": "22", "nombre": "CAMELLO"},
    {"id": 23, "numero": "23", "nombre": "CEBRA"},
    {"id": 24, "numero": "24", "nombre": "IGUANA"},
    {"id": 25, "numero": "25", "nombre": "GALLINA"},
    {"id": 26, "numero": "26", "nombre": "VACA"},
    {"id": 27, "numero": "27", "nombre": "PERRO"},
    {"id": 28, "numero": "28", "nombre": "ZAMURO"},
    {"id": 29, "numero": "29", "nombre": "ELEFANTE"},
    {"id": 30, "numero": "30", "nombre": "CAIMAN"},
    {"id": 31, "numero": "31", "nombre": "LAPA"},
    {"id": 32, "numero": "32", "nombre": "ARDILLA"},
    {"id": 33, "numero": "33", "nombre": "PESCADO"},
    {"id": 34, "numero": "34", "nombre": "VENADO"},
    {"id": 35, "numero": "35", "nombre": "JIRAFA"},
    {"id": 36, "numero": "36", "nombre": "CULEBRA"},
]

LOTERIAS = [
    {"nombre": "lotto_activo", "hora_inicio": "08:00", "hora_fin": "19:00", "intervalo": 60},
    {"nombre": "la_granjita", "hora_inicio": "08:00", "hora_fin": "19:00", "intervalo": 60},
    {"nombre": "selvaplus", "hora_inicio": "08:00", "hora_fin": "19:00", "intervalo": 60},
]
