ANIMALES_HARDCODE = [
    {"id": "0",  "numero": "0",  "nombre": "DELFIN",   "icono": "fa-fish"},
    {"id": "00", "numero": "00", "nombre": "BALLENA",  "icono": "fa-fish"},
    {"id": "1",  "numero": "01", "nombre": "CARNERO",  "icono": "fa-horse-head"},
    {"id": "2",  "numero": "02", "nombre": "TORO",     "icono": "fa-cow"},
    {"id": "3",  "numero": "03", "nombre": "CIEMPIES", "icono": "fa-bug"},
    {"id": "4",  "numero": "04", "nombre": "ALACRAN",  "icono": "fa-bug"},
    {"id": "5",  "numero": "05", "nombre": "LEON",     "icono": "fa-paw"},
    {"id": "6",  "numero": "06", "nombre": "RANA",     "icono": "fa-dragon"},
    {"id": "7",  "numero": "07", "nombre": "PERICO",   "icono": "fa-dove"},
    {"id": "8",  "numero": "08", "nombre": "RATON",    "icono": "fa-otter"},
    {"id": "9",  "numero": "09", "nombre": "AGUILA",   "icono": "fa-feather"},
    {"id": "10", "numero": "10", "nombre": "TIGRE",    "icono": "fa-paw"},
    {"id": "11", "numero": "11", "nombre": "GATO",     "icono": "fa-cat"},
    {"id": "12", "numero": "12", "nombre": "CABALLO",  "icono": "fa-horse"},
    {"id": "13", "numero": "13", "nombre": "MONO",     "icono": "fa-paw"},
    {"id": "14", "numero": "14", "nombre": "PALOMA",   "icono": "fa-dove"},
    {"id": "15", "numero": "15", "nombre": "ZORRO",    "icono": "fa-paw"},
    {"id": "16", "numero": "16", "nombre": "OSO",      "icono": "fa-paw"},
    {"id": "17", "numero": "17", "nombre": "PAVO",     "icono": "fa-kiwi-bird"},
    {"id": "18", "numero": "18", "nombre": "BURRO",    "icono": "fa-horse"},
    {"id": "19", "numero": "19", "nombre": "CHIVO",    "icono": "fa-paw"},
    {"id": "20", "numero": "20", "nombre": "COCHINO",  "icono": "fa-piggy-bank"},
    {"id": "21", "numero": "21", "nombre": "GALLO",    "icono": "fa-kiwi-bird"},
    {"id": "22", "numero": "22", "nombre": "CAMELLO",  "icono": "fa-horse"},
    {"id": "23", "numero": "23", "nombre": "CEBRA",    "icono": "fa-paw"},
    {"id": "24", "numero": "24", "nombre": "IGUANA",   "icono": "fa-lizard"},
    {"id": "25", "numero": "25", "nombre": "GALLINA",  "icono": "fa-kiwi-bird"},
    {"id": "26", "numero": "26", "nombre": "VACA",     "icono": "fa-cow"},
    {"id": "27", "numero": "27", "nombre": "PERRO",    "icono": "fa-dog"},
    {"id": "28", "numero": "28", "nombre": "ZAMURO",   "icono": "fa-feather"},
    {"id": "29", "numero": "29", "nombre": "ELEFANTE", "icono": "fa-hippo"},
    {"id": "30", "numero": "30", "nombre": "CAIMAN",   "icono": "fa-lizard"},
    {"id": "31", "numero": "31", "nombre": "LAPA",     "icono": "fa-paw"},
    {"id": "32", "numero": "32", "nombre": "ARDILLA",  "icono": "fa-paw"},
    {"id": "33", "numero": "33", "nombre": "PESCADO",  "icono": "fa-fish"},
    {"id": "34", "numero": "34", "nombre": "VENADO",   "icono": "fa-paw"},
    {"id": "35", "numero": "35", "nombre": "JIRAFA",   "icono": "fa-paw"},
    {"id": "36", "numero": "36", "nombre": "CULEBRA",  "icono": "fa-worm"},
]

LOTERIAS = [
    {"nombre": "lotto_activo", "hora_inicio": "08:00", "hora_fin": "19:00", "intervalo": 60},
    {"nombre": "la_granjita", "hora_inicio": "08:00", "hora_fin": "19:00", "intervalo": 60},
    {"nombre": "selvaplus", "hora_inicio": "08:00", "hora_fin": "19:00", "intervalo": 60},
]
